#!/bin/sh

##
## This startup file is automatically generated by tools/scripts/createScript.pl
##
. "$(dirname $0)/../../setEnv.sh"

HOME_DIR=/home/hfxdev/sa
cd ${HOME_DIR}

JAR_DIR=${HOME_DIR}/3rdlibs
CLASS_PATH=${HOME_DIR}/bin
MAIN_CLASS=org.marketcetera.strategyagent.StrategyAgent

THE_CLASSPATH=./conf

for file in `ls -1 ./lib/*.jar`
do
    THE_CLASSPATH=${THE_CLASSPATH}:${file}
done

#-Dport=7496\
JAVA_ARGS=" -Xms384m -Xmx600m -Dorg.marketcetera.appDir=. -Dstrategy.classpath=./src -Dinput.symbols=./conf/xlk.us.csv -Dibconf.file=./conf/conf-base.properties -DtickFrequency=1 -Dfile.encoding=UTF-8 -Dport=4001 -DclientId=9"

echo "java ${JAVA_ARGS} -classpath .:${THE_CLASSPATH} $MAIN_CLASS"

java ${JAVA_ARGS} -classpath .:${THE_CLASSPATH} $MAIN_CLASS $*
